# -*- coding: utf-8 -*-
"""Agricultural Data Web Scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w3ep3PEbSz7gZDOhkmCBEnIl6TzxYT71
"""

!pip install -q requests beautifulsoup4 lxml selenium pandas openpyxl duckduckgo-search newspaper3k trafilatura langdetect aiohttp asyncio nest-asyncio

import requests
from bs4 import BeautifulSoup
import pandas as pd
import json
import re
import time
import os
from urllib.parse import urljoin, urlparse, quote_plus
from datetime import datetime
import asyncio
import aiohttp
import nest_asyncio
from duckduckgo_search import DDGS
import trafilatura
from newspaper import Article
import warnings
warnings.filterwarnings('ignore')

# Enable nested asyncio for Colab
nest_asyncio.apply()

class AgriculturalDataScraper:
    def __init__(self):
        self.session = requests.Session()
        self.session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
            'Accept-Language': 'en-US,en;q=0.5',
            'Accept-Encoding': 'gzip, deflate',
            'Connection': 'keep-alive',
        })
        self.extracted_data = []
        self.failed_urls = []

    def search_additional_resources(self, crop_name, country, varieties):
        """Search for additional agricultural resources using DuckDuckGo"""
        print(f"🔍 Searching for additional resources for {crop_name} in {country}")

        search_queries = [
            f"{crop_name} varieties {country} agricultural data",
            f"{crop_name} cultivation {country} statistics",
            f"{crop_name} production {country} yield data",
            f"{' '.join(varieties)} {crop_name} {country}"
        ]

        additional_urls = set()

        with DDGS() as ddgs:
            for query in search_queries:
                try:
                    results = ddgs.text(query, max_results=10)
                    for result in results:
                        url = result.get('href', '')
                        if url and self._is_agricultural_url(url):
                            additional_urls.add(url)
                    time.sleep(1)  # Rate limiting
                except Exception as e:
                    print(f"Search error for query '{query}': {e}")

        print(f"Found {len(additional_urls)} additional resources")
        return list(additional_urls)

    def _is_agricultural_url(self, url):
        """Check if URL is likely to contain agricultural data"""
        agricultural_domains = [
            'fao.org', 'usda.gov', 'agricultural', 'farming', 'crop',
            'ministry', 'agriculture', 'research', 'extension', 'agri'
        ]
        url_lower = url.lower()
        return any(domain in url_lower for domain in agricultural_domains)

    async def extract_with_trafilatura(self, url):
        """Extract clean text using trafilatura"""
        try:
            async with aiohttp.ClientSession() as session:
                async with session.get(url) as response:
                    html = await response.text()

            extracted = trafilatura.extract(
                html,
                include_tables=True,
                include_comments=False,
                output_format='json'
            )

            if extracted:
                data = json.loads(extracted)
                return {
                    'title': data.get('title', ''),
                    'text': data.get('text', ''),
                    'date': data.get('date', ''),
                    'url': url
                }
        except Exception as e:
            print(f"Trafilatura extraction error for {url}: {e}")
        return None

    async def extract_with_newspaper(self, url):
        """Extract article data using newspaper3k"""
        try:
            article = Article(url)
            article.download()
            article.parse()

            return {
                'title': article.title,
                'text': article.text,
                'authors': article.authors,
                'publish_date': str(article.publish_date) if article.publish_date else '',
                'url': url
            }
        except Exception as e:
            print(f"Newspaper extraction error for {url}: {e}")
        return None

    def extract_structured_data(self, soup, url):
        """Extract structured agricultural data"""
        data = {
            'url': url,
            'title': '',
            'tables': [],
            'lists': [],
            'text_content': '',
            'metadata': {}
        }

        # Extract title
        title_tag = soup.find('title')
        if title_tag:
            data['title'] = title_tag.get_text().strip()

        # Extract tables
        tables = soup.find_all('table')
        for i, table in enumerate(tables):
            table_data = []
            rows = table.find_all('tr')
            for row in rows:
                cells = row.find_all(['td', 'th'])
                row_data = [cell.get_text().strip() for cell in cells]
                if row_data:
                    table_data.append(row_data)

            if table_data:
                data['tables'].append({
                    'table_index': i,
                    'data': table_data,
                    'headers': table_data[0] if table_data else []
                })

        # Extract lists
        lists = soup.find_all(['ul', 'ol'])
        for i, list_elem in enumerate(lists):
            items = [li.get_text().strip() for li in list_elem.find_all('li')]
            if items:
                data['lists'].append({
                    'list_index': i,
                    'type': list_elem.name,
                    'items': items
                })

        # Extract meta information
        meta_tags = soup.find_all('meta')
        for meta in meta_tags:
            if meta.get('name'):
                data['metadata'][meta.get('name')] = meta.get('content', '')

        # Extract main text content
        main_content = soup.find('main') or soup.find('article') or soup.find('div', class_=re.compile(r'content|main|body'))
        if main_content:
            data['text_content'] = main_content.get_text().strip()
        else:
            data['text_content'] = soup.get_text().strip()

        return data

    def filter_relevant_data(self, data, crop_name, varieties):
        """Filter data based on crop name and varieties"""
        crop_keywords = [crop_name.lower()] + [v.lower() for v in varieties]

        def is_relevant_text(text):
            text_lower = text.lower()
            return any(keyword in text_lower for keyword in crop_keywords)

        filtered_data = data.copy()

        # Filter tables
        relevant_tables = []
        for table in data['tables']:
            table_text = ' '.join([' '.join(row) for row in table['data']]).lower()
            if is_relevant_text(table_text):
                relevant_tables.append(table)
        filtered_data['tables'] = relevant_tables

        # Filter lists
        relevant_lists = []
        for list_item in data['lists']:
            list_text = ' '.join(list_item['items']).lower()
            if is_relevant_text(list_text):
                relevant_lists.append(list_item)
        filtered_data['lists'] = relevant_lists

        # Mark relevance
        filtered_data['is_relevant'] = is_relevant_text(data['text_content']) or relevant_tables or relevant_lists

        return filtered_data

    async def scrape_url(self, url, crop_name, varieties):
        """Comprehensive URL scraping"""
        print(f"📄 Processing: {url}")

        try:
            # Primary extraction with requests + BeautifulSoup
            response = self.session.get(url, timeout=30)
            response.raise_for_status()

            soup = BeautifulSoup(response.content, 'lxml')
            structured_data = self.extract_structured_data(soup, url)

            # Secondary extraction with trafilatura
            trafilatura_data = await self.extract_with_trafilatura(url)

            # Tertiary extraction with newspaper
            newspaper_data = await self.extract_with_newspaper(url)

            # Combine all extraction methods
            combined_data = {
                'url': url,
                'structured': structured_data,
                'trafilatura': trafilatura_data,
                'newspaper': newspaper_data,
                'extraction_timestamp': datetime.now().isoformat()
            }

            # Filter for relevance
            filtered_data = self.filter_relevant_data(structured_data, crop_name, varieties)
            combined_data['structured'] = filtered_data

            return combined_data

        except Exception as e:
            print(f"❌ Error processing {url}: {e}")
            self.failed_urls.append({'url': url, 'error': str(e)})
            return None

    async def process_all_urls(self, urls, crop_name, varieties):
        """Process all URLs concurrently"""
        print(f"🚀 Starting extraction for {len(urls)} URLs")

        # Process URLs in batches to avoid overwhelming servers
        batch_size = 5
        all_results = []

        for i in range(0, len(urls), batch_size):
            batch = urls[i:i + batch_size]
            print(f"Processing batch {i//batch_size + 1}/{(len(urls)-1)//batch_size + 1}")

            tasks = [self.scrape_url(url, crop_name, varieties) for url in batch]
            batch_results = await asyncio.gather(*tasks, return_exceptions=True)

            for result in batch_results:
                if result and not isinstance(result, Exception):
                    all_results.append(result)

            # Rate limiting between batches
            if i + batch_size < len(urls):
                await asyncio.sleep(2)

        self.extracted_data = all_results
        print(f"✅ Extraction completed! Processed {len(all_results)} URLs successfully")
        return all_results

    def save_data(self, crop_name, country, output_formats=['json', 'excel', 'csv']):
        """Save extracted data in multiple formats"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        base_filename = f"{crop_name}_{country}_{timestamp}"

        saved_files = []

        # Prepare summary data
        summary_data = []
        detailed_tables = []

        for item in self.extracted_data:
            url = item['url']
            structured = item.get('structured', {})

            # Summary row
            summary_row = {
                'URL': url,
                'Title': structured.get('title', ''),
                'Is_Relevant': structured.get('is_relevant', False),
                'Tables_Count': len(structured.get('tables', [])),
                'Lists_Count': len(structured.get('lists', [])),
                'Text_Length': len(structured.get('text_content', '')),
                'Extraction_Time': item.get('extraction_timestamp', '')
            }
            summary_data.append(summary_row)

            # Detailed table data
            for table in structured.get('tables', []):
                for row_idx, row in enumerate(table['data']):
                    detailed_row = {
                        'URL': url,
                        'Table_Index': table['table_index'],
                        'Row_Index': row_idx,
                        'Is_Header': row_idx == 0
                    }
                    for col_idx, cell in enumerate(row):
                        detailed_row[f'Column_{col_idx}'] = cell
                    detailed_tables.append(detailed_row)

        # Save JSON
        if 'json' in output_formats:
            json_file = f"{base_filename}.json"
            with open(json_file, 'w', encoding='utf-8') as f:
                json.dump({
                    'crop_name': crop_name,
                    'country': country,
                    'extraction_summary': {
                        'total_urls': len(self.extracted_data),
                        'failed_urls': len(self.failed_urls),
                        'extraction_timestamp': timestamp
                    },
                    'detailed_data': self.extracted_data,
                    'failed_urls': self.failed_urls
                }, f, indent=2, ensure_ascii=False)
            saved_files.append(json_file)

        # Save Excel
        if 'excel' in output_formats and summary_data:
            excel_file = f"{base_filename}.xlsx"
            with pd.ExcelWriter(excel_file, engine='openpyxl') as writer:
                # Summary sheet
                pd.DataFrame(summary_data).to_excel(writer, sheet_name='Summary', index=False)

                # Detailed tables sheet
                if detailed_tables:
                    pd.DataFrame(detailed_tables).to_excel(writer, sheet_name='Tables', index=False)

                # Failed URLs sheet
                if self.failed_urls:
                    pd.DataFrame(self.failed_urls).to_excel(writer, sheet_name='Failed_URLs', index=False)

            saved_files.append(excel_file)

        # Save CSV
        if 'csv' in output_formats and summary_data:
            csv_file = f"{base_filename}_summary.csv"
            pd.DataFrame(summary_data).to_csv(csv_file, index=False, encoding='utf-8')
            saved_files.append(csv_file)

            if detailed_tables:
                csv_tables_file = f"{base_filename}_tables.csv"
                pd.DataFrame(detailed_tables).to_csv(csv_tables_file, index=False, encoding='utf-8')
                saved_files.append(csv_tables_file)

        return saved_files

# Main execution function
async def main():
    """Main function to run the scraper"""

    # USER INPUTS - MODIFY THESE VALUES
    crop_name = "Rice"  # Change this to your crop
    country = "India"   # Change this to your country
    varieties = ["Basmati", "Jasmine", "Arborio", "Wild Rice"]  # Change to your varieties

    # Agricultural resource URLs - ADD YOUR URLs HERE
    resource_urls = [
        "https://www.fao.org/faostat/en/",
        "https://www.usda.gov/topics/farming",
        # Add your specific URLs here
    ]

    print("🌾 Agricultural Data Web Scraper Starting...")
    print(f"Crop: {crop_name}")
    print(f"Country: {country}")
    print(f"Varieties: {', '.join(varieties)}")
    print(f"Initial URLs: {len(resource_urls)}")

    # Initialize scraper
    scraper = AgriculturalDataScraper()

    # Search for additional resources
    additional_urls = scraper.search_additional_resources(crop_name, country, varieties)
    all_urls = list(set(resource_urls + additional_urls))

    print(f"Total URLs to process: {len(all_urls)}")

    # Process all URLs
    results = await scraper.process_all_urls(all_urls, crop_name, varieties)

    # Save results
    saved_files = scraper.save_data(crop_name, country)

    print("\n📊 EXTRACTION COMPLETE!")
    print(f"Successfully processed: {len(results)} URLs")
    print(f"Failed URLs: {len(scraper.failed_urls)}")
    print(f"Saved files: {saved_files}")

    # Display sample of extracted data
    if results:
        print("\n📋 Sample of extracted data:")
        sample = results[0]
        print(f"URL: {sample['url']}")
        print(f"Title: {sample['structured'].get('title', 'N/A')}")
        print(f"Tables found: {len(sample['structured'].get('tables', []))}")
        print(f"Lists found: {len(sample['structured'].get('lists', []))}")

    return scraper, saved_files

# Run the scraper
if __name__ == "__main__":
    # Execute the main function
    scraper, files = await main()

    # Optional: Download files to local machine (for Colab)
    from google.colab import files as colab_files

    print("\n📥 Downloading files to your local machine...")
    for file in files:
        if os.path.exists(file):
            colab_files.download(file)
            print(f"Downloaded: {file}")

# Optional: Advanced analysis function
def analyze_extracted_data(scraper):
    """Analyze the extracted data for insights"""
    if not scraper.extracted_data:
        print("No data to analyze")
        return

    print("\n🔍 DATA ANALYSIS SUMMARY:")

    total_tables = sum(len(item['structured'].get('tables', [])) for item in scraper.extracted_data)
    total_lists = sum(len(item['structured'].get('lists', [])) for item in scraper.extracted_data)
    relevant_items = sum(1 for item in scraper.extracted_data if item['structured'].get('is_relevant', False))

    print(f"Total tables extracted: {total_tables}")
    print(f"Total lists extracted: {total_lists}")
    print(f"Relevant content found in: {relevant_items}/{len(scraper.extracted_data)} URLs")

    # Show URLs with most content
    url_content_scores = []
    for item in scraper.extracted_data:
        score = len(item['structured'].get('tables', [])) * 3 + len(item['structured'].get('lists', []))
        url_content_scores.append((item['url'], score))

    url_content_scores.sort(key=lambda x: x[1], reverse=True)

    print(f"\n🏆 Top 5 URLs by content richness:")
    for url, score in url_content_scores[:5]:
        print(f"Score {score}: {url}")

analyze_extracted_data(scraper)

